# Change these first
owner: PnPH # Your GitHub username
repo: UpDB # Your GitHub repository name

# Add your sites here
sites:
  - name: Source
    url: $WP_SUR
  - name: WP Nur
    url: $WP_NUR
  - name: WP Far
    url: $WP_FAR
  - name: WP ERBM
    url: $WP_ERBM

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UpDB
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: upDB - Uptime Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
